import chalk from 'chalk';
import * as fs from 'fs/promises';
import * as path from 'path';
import { spawn } from 'child_process';
import { ConfigManager } from '../utils/config.js';

const DEFAULT_TEMPLATE = `# {PROJECT_NAME} - Documentation

<!--
  ReDoc Custom Template

  Available variables:
  - {PROJECT_NAME}: Name of the project
  - {BRANCH_NAME}: Current branch name
  - {DATE}: Generation date
  - {COMMITS_SUMMARY}: Summary of commits
  - {BRAIN_DUMP}: Brain dump answers
  - {CHANGES_DETAIL}: Detailed changes from commits

  Feel free to customize this template as you wish.
  The sections below are suggestions - modify or remove as needed.
-->

## Overview

{BRAIN_DUMP}

## Changes Summary

{COMMITS_SUMMARY}

## Technical Details

{CHANGES_DETAIL}

---
*Generated by ReDoc on {DATE}*
`;

/**
 * Template command - create or edit documentation template
 */
export async function templateCommand(): Promise<void> {
  const configManager = new ConfigManager();

  // Check if ReDoc is initialized
  const isInitialized = await configManager.isInitialized();
  if (!isInitialized) {
    console.log(chalk.red('Error: ReDoc is not initialized.'));
    console.log(chalk.gray('Run "redoc init" first.'));
    process.exit(1);
  }

  const config = await configManager.load();
  const projectRoot = process.cwd();
  const templateFile = '.redoc-template.md';
  const templatePath = config.templatePath || path.join(projectRoot, templateFile);

  // Check if template file exists
  let templateExists = false;
  try {
    await fs.access(templatePath);
    templateExists = true;
  } catch {
    // File doesn't exist
  }

  // Create template if it doesn't exist
  if (!templateExists) {
    console.log(chalk.blue('Creating new template file...'));
    await fs.writeFile(templatePath, DEFAULT_TEMPLATE, 'utf-8');
    console.log(chalk.green(`✓ Template created at ${templateFile}`));

    // Update config with template path
    await configManager.update({ templatePath });
  }

  // Get editor from config or environment
  const editor = config.editor || process.env.EDITOR || 'nano';

  console.log(chalk.blue(`\nOpening template in ${editor}...\n`));
  console.log(chalk.gray('Available variables:'));
  console.log(chalk.gray('  {PROJECT_NAME}    - Name of the project'));
  console.log(chalk.gray('  {BRANCH_NAME}     - Current branch name'));
  console.log(chalk.gray('  {DATE}            - Generation date'));
  console.log(chalk.gray('  {COMMITS_SUMMARY} - Summary of commits'));
  console.log(chalk.gray('  {BRAIN_DUMP}      - Brain dump answers'));
  console.log(chalk.gray('  {CHANGES_DETAIL}  - Detailed changes from commits'));
  console.log('');

  // Open editor
  const editorParts = editor.split(' ');
  const editorCmd = editorParts[0];
  const editorArgs = [...editorParts.slice(1), templatePath];

  const child = spawn(editorCmd, editorArgs, {
    stdio: 'inherit',
    shell: true
  });

  child.on('close', (code) => {
    if (code === 0) {
      console.log(chalk.green('\n✓ Template saved'));
      console.log(chalk.gray(`  Path: ${templatePath}`));
    } else {
      console.log(chalk.yellow('\nEditor closed without saving or with error'));
    }
  });

  child.on('error', (error) => {
    console.log(chalk.red(`\nFailed to open editor: ${error.message}`));
    console.log(chalk.gray(`Template location: ${templatePath}`));
    console.log(chalk.gray('You can edit it manually or change your editor with:'));
    console.log(chalk.gray('  redoc config set editor "code --wait"'));
  });
}
